FROM ghcr.io/linuxcontainers/alpine:latest as stage-base

RUN apk add openssh
CMD ssh "nadir@$(cat ${NADIR_SERVER_ADDRESS_PATH})" -p "${NADIR_SERVER_SSH_PORT}" -R "*:${NADIR_CLIENT_REMOTE_PORT}:${NADIR_CLIENT_FORWARD_TO_HOST}:${NADIR_CLIENT_FORWARD_TO_PORT}" -i "${NADIR_CLIENT_SSH_IDENTITY_PATH}" -v -o ExitOnForwardFailure=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o RequestTTY=no -o SessionType=none -o ServerAliveCountMax=21 -o ServerAliveInterval=15

# BUILD DEV IMAGE
# Modify the base image for development
FROM stage-base AS stage-dev

ENV CONTAINER_ENV="dev"

# BUILD PROD IMAGE
# Modify the base image for production
FROM stage-base AS stage-prod

ENV CONTAINER_ENV="prod"
